# Johnny Li
# Assignment 2
# Makefile: UnencryptedIM CPP

# --- macros
CC=g++

# --- targets
# --- makefile
UnencryptedIM: UnencryptedIM.o
	$(CC) -o UnencryptedIM UnencryptedIM.o

UnencryptedIM.o: UnencryptedIM.cpp
	$(CC) -c UnencryptedIM.cpp

